services:
  mongodb_container:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - tutorial
  frontend:
    build: frontend
    ports:
      - 8000:8000
    networks:
      - tutorial
  process:
    build: process
    networks:
      - tutorial
  delivery:
    build: delivery
    networks:
      - tutorial
networks:
  tutorial:
    ipam:
      driver: default
volumes:
  mongodb_data_container: